import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Hero, AttackType, PrimaryAttr } from "@/types";
import { twMerge } from "tailwind-merge";
import { Button } from "@/components/Button";
import { AgiIcon, IntIcon, StrIcon, MeleeIcon, RangedIcon } from "@/components/Icons";

export default function Home() {
  const [heroes, setHeroes] = useState<Hero[] | null>(null);
  const [primaryAttr, setPrimaryAttr] = useState<PrimaryAttr | null>(null);
  const [attackType, setAttackType] = useState<AttackType | null>(null);

  useEffect(() => {
    fetch("https://api.opendota.com/api/heroStats")
      .then((res) => res.json())
      .then((data: Hero[]) => {
        setHeroes(data);
      })
      .catch((error) => console.error(error));
  }, []);

  function handleAttackType(newAttackType: AttackType) {
    setAttackType((attackType) => (attackType === newAttackType ? null : newAttackType));
  }

  function handleAttr(newAttr: PrimaryAttr) {
    setPrimaryAttr((primaryAttr) => (primaryAttr === newAttr ? null : newAttr));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={twMerge(
          "font-inter",
          "flex flex-col justify-center items-center w-full",
          "bg-gradient-to-tr from-black via-deg to-black",
          primaryAttr === PrimaryAttr.Str && "bg-gradient-to-tr from-black via-red-800 to-black",
          primaryAttr === PrimaryAttr.Agi && "bg-gradient-to-tr from-black via-green-800 to-black",
          primaryAttr === PrimaryAttr.Int && "bg-gradient-to-tr from-black via-blue-800 to-black"
        )}
      >
        <div>
          <div className="flex flex-col justify-center items-center m-10 gap-4">
            {/* ATTRIBUTE FILTERS */}

            <div className="flex gap-6">
              <Button
                className={twMerge(
                  "border-str text-str hover:shadow-str",
                  primaryAttr === PrimaryAttr.Str && "bg-str text-black hover:shadow-red-500"
                )}
                onClick={() => {
                  handleAttr(PrimaryAttr.Str);
                }}
                icon={PrimaryAttr.Str}
              >
                <StrIcon fill={primaryAttr === PrimaryAttr.Str ? "black" : "#B62B24"} />
                STRENGTH
              </Button>

              <Button
                className={twMerge(
                  "border-agi text-agi hover:shadow-agi",
                  primaryAttr === PrimaryAttr.Agi && "bg-agi text-black hover:shadow-green-500"
                )}
                onClick={() => {
                  handleAttr(PrimaryAttr.Agi);
                }}
                icon={PrimaryAttr.Agi}
              >
                <AgiIcon fill={primaryAttr === PrimaryAttr.Agi ? "black" : "#5BEF36"} />
                AGILITY
              </Button>

              <Button
                className={twMerge(
                  "border-int text-int hover:shadow-int",
                  primaryAttr === PrimaryAttr.Int && "bg-int text-black hover:shadow-blue-300"
                )}
                onClick={() => {
                  handleAttr(PrimaryAttr.Int);
                }}
                icon={PrimaryAttr.Int}
              >
                <IntIcon fill={primaryAttr === PrimaryAttr.Int ? "black" : "#36ACEF"} />
                INTELLIGENCE
              </Button>
            </div>

            {/* ATTACK TYPE FILTER */}
            <div className="flex gap-5 m-1">
              <Button
                className={twMerge(
                  "border-white text-white hover:shadow-white",
                  attackType === AttackType.Melee && "bg-white text-black hover:shadow-gray-300"
                )}
                onClick={() => {
                  handleAttackType(AttackType.Melee);
                }}
                icon={AttackType.Melee}
              >
                <MeleeIcon fill={attackType === AttackType.Melee ? "black" : "white"} />
                MELEE
              </Button>

              <Button
                className={twMerge(
                  "border-white text-white hover:shadow-white",
                  attackType === AttackType.Ranged && "bg-white text-black hover:shadow-gray-300"
                )}
                onClick={() => {
                  handleAttackType(AttackType.Ranged);
                }}
                icon={AttackType.Ranged}
              >
                <RangedIcon fill={attackType === AttackType.Ranged ? "black" : "white"} />
                RANGED
              </Button>
            </div>
          </div>

          {/* RESULTS */}
          <div className="grid grid-cols-1 gap-4 md:grid-cols-8 lg:gap-6 text-white">
            {heroes
              ?.filter((value) => {
                return (
                  // filtro:
                  // Se o 1º for null(true), ele pula pra segunda condição.
                  // Se possuir um valor(false), ele filtra baseado na condição imposta.
                  // A mesma regra repete-se para as duas linhas.
                  (!attackType || value.attack_type === attackType) &&
                  (!primaryAttr || value.primary_attr === primaryAttr)
                );
              })
              .map((value) => {
                return (
                  <div key={value.id}>
                    <Image
                      alt={value.localized_name + " Icon"}
                      src={"https://api.opendota.com" + value.img}
                      width={256}
                      height={144}
                      className="w-32 h-24 object-cover"
                      priority
                    />
                    <ul>
                      <li>{value.localized_name}</li>
                    </ul>
                  </div>
                );
              })}
          </div>
        </div>
      </main>
    </>
  );
}
